### ISSUE TITLE
`test-application` does not set `output.arn` is not set if fails

### ISSUE THREAD

**Issue by gmazzo** [aardsoft/aws-devicefarm#16]
I'm currently using `${{ steps.adf.outputs.arn }}` with
```yaml
      - id: adf
        name: Amazon Device Farm
        uses: realm/aws-devicefarm/test-application@v1
        with:
            ...
```
to reconstruct the test run URL to provide feedback to the users. But it seems when the step fails, all `outputs` are empty
